### ISSUE TITLE
Latest ledger ethereum app upgrade to 1.2.13 blows away user's contract data setting

### ISSUE THREAD

**Issue by nottoseethesun** [LedgerHQ/app-ethereum#102]
Contract data is turned off even if it was previously on, when updating the ledger nano s or ledger x .   Thus, many interactions that were working for the user will no longer work, until somehow they figure out the cryptic error message and then manually allow contract data on the ledger device.

Instead, existing settings should be preserved where they are still supported in the new version.

**Comment by cappaberra** [comment]
@pscott, was there a PR merged in that you can link to this issue?

**Comment by pscott** [comment]
@cappaberra Hi!
There was no PR merged :( 
I closed this issue for two reasons:

1. Unfortunately, this is not an issue we plan on fixing anytime soon.
2. If this were to be fixed, it would have to come from the OS side of things ([BOLOS](https://www.ledger.com/academy/security/our-custom-operating-system-bolos)).

In the meantime, users will have to remember to put back their settings :(
