### ISSUE TITLE
Ledger nano S can`t interact with Eth2 Staking Smart Contract (Metamask)

### ISSUE THREAD

**Issue by victorelec14** [LedgerHQ/app-ethereum#116]
#### Ledger Live Version and Operating System

- tested on Ledger Live **Ledger nano X, firmware 1.2.4-5 , ETH 1.6.1**
- Platform and version: **Windows 10**

#### Steps to reproduce the behavior

Ledger cannot interact with the Eth2 SmartContrat (launchpad), the contract is not signed.

```
Contract data: Allow contract data in transactions -> Allowed
Ledger nano X,
Firmware 1.2.4-5 , 
App ETH 1.6.1
```

I have tried with different browsers, with Brave, Chrome + Metamask and with another usb cable.

the problem is happening to many people with the latest firmware.

```
MetaMask - RPC Error: Error: TransportStatusError: Ledger device: Condition of use not satisfied (denied by the user?) (0x6985) {code: -32603, message: "Error: TransportStatusError: Ledger device: Condit… use not satisfied (denied by the user?) (0x6985)", stack: "Error: Error: TransportStatusError: Ledger device:… use not satisfied (denied by the user?) (0x6985)"}
```

![image](https://user-images.githubusercontent.com/543450/100472365-66c42100-30dc-11eb-895a-90c10714e0ba.png)

![image](https://user-images.githubusercontent.com/543450/100473012-adfee180-30dd-11eb-86b9-c206613508c6.png)

More people with the same problem:
https://www.reddit.com/r/ledgerwallet/comments/k0l294/unable_to_interact_with_eth2_staking_contract/

**Comment by btchip** [comment]
Could you verify if the raw TX can be signed by a different wallet ?

**Comment by victorelec14** [comment]
@btchip  How do I do that? Several comment that they have no problems with the ETH 1.6.0 App, it seems that version 1.6.1 is broken.

on the testnet I had no problem signing with metamask.

Some people comment that they have sent the ETH to the Metamask wallet and from there if they can sign the transaction.

Thank you

**Comment by btchip** [comment]
I don't have step by step instructions as I'm using internal tools for that. Do you have an example of a raw TX or the data of the TX that's rejected so I can try to reproduce ? I haven't been able to do that so far.

**Comment by victorelec14** [comment]
I'm sorry I can't give you the information of the transaction because I don't know if it would endanger my wallet, you would have to try to do the launchpad process on eth2.

I think I will have to do what they say in discord, which is to pass the ETH to the metamask wallet and from there sign.

I've also just tried Firefox and another computer and the problem is the same.

Is it possible to rollback the Eth App manually?

thx

**Comment by martinkou** [comment]
Confirmed to have the same issue on ETH 1.6.1 and Firmware 1.2.4-5 as well.

This is a regression bug, I was able to make the Eth2 staking contract deposit on ETH 1.2.x (I forgot exactly which version, but it was old) and Firmware 1.2.4-1 before.

**Comment by martinkou** [comment]
Also, the TX could be signed by importing the same seed phrase to MetaMask. So it's clearly a Ledger problem.

Here's the MetaMask signed TX, which Ledger w/ ETH 1.6.1 wasn't able to sign.
https://etherscan.io/tx/0x5589da09f048cc42542bdd4e4c79aac4910b50a79fd844da4c35025b39157d10

One more thing... I was able to sign the GoETH deposit TX on Goerli test net on the new firmware. So the problem (unfortunately) seems to happen only with the mainnet Eth2 staking contract.

**Comment by btchip** [comment]
I couldn't reproduce with the linked transaction. What's the error in Metamask ?

**Comment by martinkou** [comment]
I got "TransportStatusError: Ledger device:Invalid data received (0x6a80)" when I attempted the mainnet transaction.

Contract data was enabled in the Ethereum app.

**Comment by btchip** [comment]
ok, so I think we'll need a simple way to sign a raw transaction to conclude, as Metamask doesn't include this fix yet https://github.com/LedgerHQ/ledgerjs/commit/dc64c0eaf4f0718ef31629d22878ada234346297

**Comment by victorelec14** [comment]
hmm then should Metamask take care of this problem? or is there any way to fix it?

Can't revert to APP Eth 1.6.0? or is there a way to install it manually?

Before December 1 (Genesis start) there will be no update, right?

Thank you

**Comment by martinkou** [comment]
The corresponding pull request on MetaMask's side is this: https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/45

**Comment by gradoj** [comment]
So is this issue rolled out?
