### ISSUE TITLE
Support for Interacting with Custom RPCs in Metamask

### ISSUE THREAD

**Issue by eatdostacos** [LedgerHQ/app-ethereum#120]
**Info:**
- Ledger Nano X (Firmware 1.2.4-5)
- Ethereum App 1.6.2
- OS: Windows 10 (20H2)

**Error:**
Currently, when I try to sign a transaction through Metamask on the xDai chain RPC with my Ledger Nano X, this happens:
![Screenshot 2020-12-09 125932](https://user-images.githubusercontent.com/64234158/101686967-a5cc6d80-3a1e-11eb-800d-09be45a47df2.png)
In the past, an error sometimes shows up saying that the Ledger can't sign it. I looked up the issue and other people talked about it on other websites, but couldn't seem to find a solution. I hope you can find a way to solve this as I would like to have the security of my Ledger while interacting with the xDai chain and I would like to move those tokens as well.
Thanks,
Nano X user

**Comment by TamtamHero** [comment]
Probably related to https://github.com/MetaMask/eth-ledger-bridge-keyring/pull/45

**Comment by eatdostacos** [comment]
I recently tried more chains in Metamask with my Ledger such as Fantom and XDai and they work now even though they hadn't in the past. I'm going to close this since it seems to have been fixed somewhere.
