### ISSUE TITLE
Ledger blue: User interface for signing message/data

### ISSUE THREAD

**Issue by RED29** [LedgerHQ/app-ethereum#121]
The UI is very difficult to handle when signing messages. This is a great security risk. A normal interacting with smart contract is about 40 - 70 pages on the Ledger Blue until you reach the last page to confirm the transaction. This leads to possible uncertainty when you don't know what you confirming. Maybe extracting data that is most importing, like the different addresses you are interacting, and maybe a better way to see how much pages there a left.

**Comment by TamtamHero** [comment]
The Blue model is not supported anymore, which means Ledger will not develop new functionalities for its apps anymore. PRs are still welcomed, though.
