### ISSUE TITLE
Support for signing old tx/message before EIP155

### ISSUE THREAD

**Issue by lewtran** [LedgerHQ/app-ethereum#124]
I tried some method for signing a transaction/message before EIP155 (chainid=0 or without chainid) but it doesn't work. The signed TX can recover but with different Address.
I'm using Ledger Nano X

**Comment by TamtamHero** [comment]
We've recently updated this helper, did you use it ? https://github.com/LedgerHQ/app-ethereum/commit/5f43cb7a59ad941d03279d31627be759c31a8ab1

**Comment by lewtran** [comment]
> We've recently updated this helper, did you use it ? [5f43cb7](https://github.com/LedgerHQ/app-ethereum/commit/5f43cb7a59ad941d03279d31627be759c31a8ab1)

Thank you for your response. It's seem fine if I use the example signTx.py, Ledger returns the correct signed rlp and it can recover the signature.
The problem comes from when I connect the Ledger with Metamask (a modified version to add custom RPC with ChainID = 0), when I try to sign a tx, Ledger returns a raw signed TX but cannot recover the tx data.
Step that I tried:
- Assign '0x00' R,S,V to the TxData (with chainId = 0)
- Encode Tx and send to Ledger
- Ledger return raw corrupted signed tx that cannot recover (maybe this is a bug?!)
But it's fine if I try assign with V 0x01 (etherum mainnet)

**Comment by lewtran** [comment]
Update: even when parse V as '0x00' or chainid = 0, the raw signed tx always returns V = '0x23'

**Comment by TamtamHero** [comment]
You should not pass any R,S,V at all (like we do in signTx.py)

**Comment by lewtran** [comment]
> You should not pass any R,S,V at all (like we do in signTx.py)

Thank you so much for your response, I've rewrite the ethtx libs to not rlp hash RSV and it works fine
