### ISSUE TITLE
Display chain id when signing transactions

### ISSUE THREAD

**Issue by MrClottom** [LedgerHQ/app-ethereum#135]
With it being more and more common that users interact with multiple chains it is extremely important that the ledger display some unique identifier so that chains can be differentiated.

As a user I need to know whether I'm signing a transaction for mainnet, ropsten, binance smart chain or xDai. Am I sending 2 ETH (~4500$), 2 BNB (~1000$) or 2 xDAI (~2$)? While additionally displaying the symbol of the specific chain instead of 'ETH' simply showing the chain id would likely be enough. Something like "Chain ID: 0x56".

The fact that one cannot discern for which chain a transaction is being signed is a major security risk.

**Comment by pscott** [comment]
Hey @MrClottom ! Thank you for your feedback.
It turns out this feature is ALMOST done: here's a link to the Pull Request that should get merged soon https://github.com/LedgerHQ/app-ethereum/pull/131 :rocket:

**Comment by pscott** [comment]
Closed this issue because the PR is already in the works :)
