### ISSUE TITLE
can sign transaction including "type" property?

### ISSUE THREAD

**Issue by Feelthewind** [LedgerHQ/app-ethereum#141]
I use ethereum app in ledger device and want to sign transaction including property "type" for klaytn network.

It throw error message "EthAppPleaseEnableContractData: Please enable Contract data on the Ethereum app Settings" and it seems to be related to error code 0x6a80 (Invalid data)

Is it not possible to sign transaction including type property with ledger ethereum app?

Transaction is like this.

chainId: 8217
data: "0x1b2ba1140000000000000000000000009eaefb09fe4aabfbe6b1ca316a3c36afc83a393f000000000000000000000000000000000000000000000000000000000000000e00000000000000000000000000000000000000000000000000000000000000600000000000000000000000000000000000000000000000000000000000000000"
from: "0x02e31a6132d338995e3236d2422318110540392c"
gasLimit: "0x8162c"
gasPrice: "0x05d21dba00"
nonce: 66
to: "0xc6a2ad8cc6e4a7e08fc37cc5954be07d499e7654"
type: "FEE_DELEGATED_SMART_CONTRACT_EXECUTION"
value: "0x9184e72a000"

**Comment by pscott** [comment]
Hi @Feelthewind . Have you tried enabling the contract data?
To do so, open your Ethereum app, go to settings and press both button so that you see `Contract Data **Allowed**`

Hope it helps!

**Comment by pscott** [comment]
Closing this :)
