### ISSUE TITLE
Amount of ETH to be sent not displaying on Ledger Nano S (bug)

### ISSUE THREAD

**Issue by jonsats** [LedgerHQ/app-ethereum#144]
Ledger Live Version and Operating System
tested on Ledger Live 2.26.1
Platform and version: ** Mac 10.13.5 **
Expected behavior
When sending ETH you should be able to see the amount of ETH being sent on the Ledger Nano S device (2.0.0)

Actual behavior
When sending ETH the Amount section shows a partial address of the destination rather than the quantity of ETH, the destination address is then shown in full as expected on the following screen.

ETH app version 1.7.5

**Comment by pscott** [comment]
Thank you @jonsats for your report. We are investigating this issue!

**Comment by pscott** [comment]
This has been fixed (`v1.7.6`) :)
