### ISSUE TITLE
Invalid ChainID when trying to swap tokens

### ISSUE THREAD

**Issue by sanchopansa** [LedgerHQ/app-ethereum#147]
Device: Ledger Nano X
Firmware: 1.3.0
Ethereum app: 1.7.8
OS: Ubuntu 18.04
MetaMask: 9.5.3

I'm experiencing a weird behavior when trying to swap a larger quantity of tokens on multiple DEXes on the Fantom blockchain. 

For example, for the FTM/DAI pair on SushiSwap and SpookySwap and for the FTM/USDC pair on SpiritSwap, if I try to swap 4722 FTM, the ChainID being displayed on the Ledger device is the correct one (250). However, if I try to swap 4723 or more FTM on all of those 3 exchanges, I'm seeing a ChainID of 0 on the device and subsequently the transaction doesn't go through.

The error being shown is the same in all cases: `Error: TransportStatusError: Ledger device: Condition of use not satisfied (denied by the user?) (0x6985)`

A similar issue with the ChainID set to 0 was reported here for Matic/Polygon: https://github.com/MetaMask/metamask-extension/issues/9510 and it seems like the 1.7.8 release has resolved it, however the Fantom issue still persists.

I have only observed the above while trying to do swaps of larger quantities of tokens using MetaMask and Ledger. If I use a MetaMask account, the private key for which is stored locally, I do not have any issue with these transactions, which leads me to believe it's a problem with the Ledger Ethereum app.

Does anyone have an insight as to what might be causing it?

**Comment by afsym** [comment]
Hello,
Thanks for reporting. We'll take a look at this issue next Tuesday.

**Comment by pscott** [comment]
@sanchopansa Hi and thanks for reporting.
Does it only happen on the Fantom blockchain? Have you ever encountered this on eth mainnet?

**Comment by pscott** [comment]
@sanchopansa Yup, definitely similar. I don't see any reason why this would only happen to Fantom blockchain (we don't really have any specific logic for chainID, so shouldn't change anything). I've been trying to reproduce it, but haven't managed to do so yet. I guess I need to buy 4723 FTM in order to make the EXACT same tx...

**Comment by sanchopansa** [comment]
If you give me an address, I will send you 5000 FTM to try it out.

**Comment by sanchopansa** [comment]
You should be receiving them shortly.

**Comment by pscott** [comment]
Ok thanks, investigating.

**Comment by pscott** [comment]
https://github.com/LedgerHQ/ledgerjs/pull/606 should fix that!

Closing :) Feel free to re-open if this bad boy shows up again (shouldn't happen once MM upgrades ledgerjs :D)

**Comment by 0xpicklerickle** [comment]
Feel like i should report this issue as the invalid chain ID is popping up again today. 

My versions:
MM - 9.5.9
Ledger ETH - 1.8.5

Chain ID shows 0 when trying to use it on Avalanche C-chain when trying to swap more than 10 avax. Could relate to chunksize issue as before.

**Comment by pscott** [comment]
> Feel like i should report this issue as the invalid chain ID is popping up again today.
> 
> My versions:
> MM - 9.5.9
> Ledger ETH - 1.8.5
> 
> Chain ID shows 0 when trying to use it on Avalanche C-chain when trying to swap more than 10 avax. Could relate to chunksize issue as before.

Hey!
Thanks for reporting this in.
I definitely think this has been fixed by [ledgerjs v5.52.1](https://github.com/LedgerHQ/ledgerjs/releases/tag/v5.52.1). The question is: has your wallet upgraded to a version higher than 5.52.1 of its ledgerjs dependency ? :D

If it has, please ping me back, this would need further investigation (but I honestly doubt that this specific problem has not been fixed! :p At least I hope so.... )

**Comment by 0xpicklerickle** [comment]
> > Feel like i should report this issue as the invalid chain ID is popping up again today.
> > My versions:
> > MM - 9.5.9
> > Ledger ETH - 1.8.5
> > Chain ID shows 0 when trying to use it on Avalanche C-chain when trying to swap more than 10 avax. Could relate to chunksize issue as before.
> 
> Hey!
> Thanks for reporting this in.
> I definitely think this has been fixed by [ledgerjs v5.52.1](https://github.com/LedgerHQ/ledgerjs/releases/tag/v5.52.1). The question is: has your wallet upgraded to a version higher than 5.52.1 of its ledgerjs dependency ? :D
> 
> If it has, please ping me back, this would need further investigation (but I honestly doubt that this specific problem has not been fixed! :p At least I hope so.... )

Hey, thanks for the quick reply. How do i go about checking my wallet's ledgerjs dependency? 
Also, would i need nodejs and yarn to update it?
