### ISSUE TITLE
EIP-1559 Support

### ISSUE THREAD

**Issue by brad-decker** [LedgerHQ/app-ethereum#150]
Greetings.

I am working on EIP-1559 support at MetaMask and am doing discovery & identifying unknowns. When we pass a transaction to hw-app-ethereum for signing we send it a serialized transaction. We use `@ethereumjs/tx` to generate the serialized transaction which will take into consideration all of the rlp encoding needed for the new fields. When we get the `v, r, s` values back from ledger we append them to the transaction. 

What work is required by Ledger to be able to support EIP-1559 and is there a tracking issue? I assume that ledger unserializes the transaction to display the data to the user on the hardware wallet. A similar question could be asked about EIP-2930 and any future transaction type added under the EIP-2718 Typed transaction envelope.

**Comment by pscott** [comment]
https://github.com/LedgerHQ/ledgerjs/pull/606 should fix the problem! Thanks for reporting this one :)

**Comment by pscott** [comment]
Got confused about issues.... my bad hahaha

**Comment by pscott** [comment]
@brad-decker Ledgerjs was recenlty updated with the [support for EIP-1559 transactions](https://github.com/LedgerHQ/ledgerjs/commit/ef2e86294d2664955b6e77e78338aeecb70dfa56). I think third party wallets will need to update their dependencies! :D
