### ISSUE TITLE
Make clearer error code

### ISSUE THREAD

**Issue by pscott** [LedgerHQ/app-ethereum#161]
Currently the code throws `0x6a80` in lots of different situations, making it hard to wallets / end users to understand what is the real problem.

Ideally we'd want a different code for every different error scenario :D

**Comment by AdarshRawat1** [comment]
Can I work on this issue.

**Comment by cedelavergne-ledger** [comment]
Closing, because addressed in https://github.com/LedgerHQ/app-ethereum/pull/578
