### ISSUE TITLE
Add test for starkware

### ISSUE THREAD

**Issue by pscott** [LedgerHQ/app-ethereum#168]
It would be nice to have tests for the starkware plugin (at least the main selectors)

**Comment by Subbitoooo** [comment]
Sure, let's create a basic test for the StarkWare plugin. For simplicity, I'll assume that the StarkWare plugin is related to cryptographic and blockchain technologies. Let's call it the "StarkWare Crypto Plugin Test."
Objective:
Evaluate the functionality and security of the StarkWare Crypto Plugin.
Steps:
1)Install the StarkWare plugin.
2)Initialize the plugin with sample configurations.
3)Verify that the initialization process completes without errors.
4)Encryption and Decryption:

Description: Test the encryption and decryption capabilities of the StarkWare plugin.
Steps:
1)Generate a random message.
2)Encrypt the message using the StarkWare plugin.
3)Decrypt the message using the StarkWare plugin.
4)Verify that the decrypted message matches the original message.
   Blockchain Interaction:

Description: Ensure the StarkWare plugin can interact with a blockchain.
Steps:
1)Connect the StarkWare plugin to a test blockchain.
2)Perform a transaction (e.g., transfer tokens) using the plugin.
3)Verify that the transaction is recorded on the blockchain.
Key menagment:
Description: Test the key management features of the StarkWare plugin.
Steps:
1)Generate a new cryptographic key pair using the plugin.
2)Verify that the key pair is securely stored.
3)Use the generated key pair for encryption and decryption.
 Error Handling:

Description: Test the plugin's response to invalid inputs or unexpected errors.
Steps:
1)Provide invalid configurations during initialization.
2)Attempt to decrypt a message with an incorrect key.
3)Verify that the plugin handles errors gracefully and provides meaningful error messages.
    Performance Testing:

Description: Evaluate the performance of the StarkWare plugin.
Steps:
1)Encrypt and decrypt a large number of messages consecutively.
2)Measure the time taken for each operation.
3)Ensure that the plugin performs efficiently under normal usage conditions.
     Note: Ensure that the test environment is set up with appropriate testing accounts, configurations, and permissions for 
     interacting with the blockchain.

      Remember, this is just a basic outline. You might need to tailor it according to the specific functionalities and features of the 
      StarkWare plugin.
      Enjoy it :)
I hope that This message will help you :)

**Comment by cedelavergne-ledger** [comment]
Closing because starkware is no more in ethereum app
