### ISSUE TITLE
Support for eth_getEncryptionPublicKey and eth_decrypt (EIP-1024)

### ISSUE THREAD

**Issue by safisynai** [LedgerHQ/app-ethereum#189]
These methods, as implemented by Metamask respectively allow a Dapp to obtain a public key appropriate for encryption, and decrypt an encrypted payload using a private key derived from an Ethereum account's private key.

At least one Dapp already makes use of these methods; Tornado.cash, which uses these to encrypt a backup copy (which is stored on-chain) of private notes required to redeem deposits.

It would be great if we could use these methods with our Ledger-backed keys :)

References:
https://github.com/ethereum/EIPs/pull/1098
https://docs.metamask.io/guide/rpc-api.html#other-rpc-methods

**Comment by colinnielsen** [comment]
Any thoughts from Ledger on this? It would be great if this was implemented

**Comment by alacombe-ledger** [comment]
Hello, thank you for this idea, it is currently not in our roadmap but we could take a look at it, probably beginning of next year.

While we are discussing Tornado.cash, feel free to have a look at https://torn.community/t/tornado-cash-in-ledger-live/1735 this would definitely help pushing these topics.

Thank you,
Adrien

**Comment by pepawel** [comment]
[Skiff](https://skiff.com/) requires this, so +1

**Comment by iknowdavid** [comment]
I'll plus one this issue too unfortunately: 401884

**Comment by firnprotocol** [comment]
bumping this; would be great to see this feature. any updates by any chance?

**Comment by cseguret-ledger** [comment]
Resolves #240

**Comment by pepawel** [comment]
@firnprotocol I'm not in a dev team, however I upgraded my Ledger's firmware today and can confirm Skiff works. It probably means the issue is resolved.

**Comment by firnprotocol** [comment]
@pepawel excellent, thanks for the heads-up—though it looks like now MetaMask needs to update itself to not throw an error in this case?  (see lined issue above)

**Comment by firnprotocol** [comment]
@pepawel saw your edits.

right, the problem is that when you call `eth_getEncryptionPublicKey` with a Ledger logged in, MetaMask throws:
```javascript
{
    code: -32603
    message: "Ledger does not support eth_getEncryptionPublicKey."
    ...
}
```
this is because of [this pull request](https://github.com/MetaMask/metamask-extension/pull/10326), which essentially defined this error behavior—under the assumption that Ledger doesn't support it.

Now that [Ledger _does_ support this](https://github.com/LedgerHQ/app-ethereum/issues/189) (see above), I think MetaMask needs to re-visit this error behavior and disable it. that's my read. i haven't gotten a response from them yet though.

**Comment by pepawel** [comment]
@firnprotocol thank you for explaining the issue, it definitely makes sense!

**Comment by jacquesvcritien** [comment]
Hi, can anyone confirm whether Ledger supports eth_getEncryptionPublicKey please?
