### ISSUE TITLE
Signing tags

### ISSUE THREAD

**Issue by willianpaixao** [LedgerHQ/app-ethereum#194]
I would like to kindly ask the maintainers to [GPG sign](https://docs.github.com/en/github/authenticating-to-github/managing-commit-signature-verification/signing-tags) the [tags](https://github.com/LedgerHQ/app-ethereum/tags) as well.

At the moment, only the [commits](https://github.com/LedgerHQ/app-ethereum/commits/master) are being signed.

**Comment by TamtamHero** [comment]
TIL :exploding_head: 
will do from now on, thanks !
