### ISSUE TITLE
Is there any way to sign personal message with no SIGN_MAGIC?

### ISSUE THREAD

**Issue by Feelthewind** [LedgerHQ/app-ethereum#197]
I want to know if there is any way to sign message with no SIGN_MAGIC prefix in handleSignPersonalMessage.

```
static const char SIGN_MAGIC[] =
    “\x19”
    “Ethereum Signed Message:\n”;

cx_hash((cx_hash_t *) &global_sha3,
                0,
                (uint8_t *) SIGN_MAGIC,
                sizeof(SIGN_MAGIC) - 1,
                NULL,
                0);

**Comment by pscott** [comment]
Hi,
As you've pointed out, `SIGN_MAGIC` is a constant that will always get hashed in `handleSignPersonalMessage`, so I believe the answer to your question is "no" ! :(
