### ISSUE TITLE
RSK plugin

### ISSUE THREAD

**Issue by john-light** [LedgerHQ/app-ethereum#206]
Ledger has an app for RSK, which is an EVM-compatible bitcoin sidechain. I could not find the repo for the RSK Ledger app. I am interested to know if there is the ability to create RSK app plugins the same way it is possible to create Ethereum app plugins, so that users can more easily understand the details of the transactions they are signing?

Reference: https://github.com/LedgerHQ/app-ethereum/blob/named-external-plugins/doc/ethapp_plugins.asc

**Comment by pscott** [comment]
the RSK app is here (a variant in the ethereum-app Makefile):
https://github.com/LedgerHQ/app-ethereum/blob/39f9253582652b1dcde5e12897c84e3b338da707/Makefile#L122-L125

I believe plugins should indeed work right off the bat with RSK and similar variants, but further testing would be needed :)
