### ISSUE TITLE
Add ThunderCore network (TT)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#250]
# Description
- [x] Symbol: TT
- [x] ChainId: 108
- [x] Website:  https://thundercore.com/#/
- [x]  Block-Explorer: https://scan.thundercore.com/
- [x] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: 1001 

# Additional comments

First PR #60

**Comment by Draghtnod** [comment]
This has already been merged here: https://github.com/LedgerHQ/app-ethereum/commit/0e3c0f9263e9339e454fff5d1d9698f743c85344
