### ISSUE TITLE
Add Dexon network (DXN)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#251]
# Description
- [X] Symbol: DXN
- [X] ChainId: 237
- [X] Website:  https://dexon.org/
- [X]  Block-Explorer: https://dexonscan.app/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: 237

# Additional comments

First PR #61

**Comment by Draghtnod** [comment]
This has already been merged here: https://github.com/LedgerHQ/app-ethereum/commit/0e3c0f9263e9339e454fff5d1d9698f743c85344
