### ISSUE TITLE
Add Solidum network (SUM)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#252]
# Description
- [X] Symbol: SUM
- [X] ChainId: 72106
- [X] Website: https://solidum.network/
- [X]  Block-Explorer: https://explorer.solidum.network/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: 997

# Additional comments

First PR #70

**Comment by vforgeoux-ledger** [comment]
Please follow the [guidelines](https://developers.ledger.com/docs/device-app/develop/code/clone#a---using-the-4460-path) for this chain to be supported.
