### ISSUE TITLE
Add Webchain network (WEB)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#253]
# Description
- [X] Symbol: WEB
- [X] ChainId: 24484
- [X] Website: https://webchain.network/
- [X]  Block-Explorer: https://explorer.webchain.network/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: 227

# Additional comments

First PR #76

**Comment by Draghtnod** [comment]
This has already been merged here: https://github.com/LedgerHQ/app-ethereum/commit/0e3c0f9263e9339e454fff5d1d9698f743c85344
