### ISSUE TITLE
Add Rupaya network (RUPX)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#254]
# Description
- [X] Symbol: RUPX
- [X] ChainId: 77
- [X] Website: https://www.rupx.io/
- [X]  Block-Explorer: https://scan.rupaya.io/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: 499

# Additional comments

First PR #92

**Comment by vforgeoux-ledger** [comment]
Please follow the [guidelines](https://developers.ledger.com/docs/device-app/develop/code/clone#a---using-the-4460-path) for this chain to be supported.
