### ISSUE TITLE
Add Wethio network (ZYN)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#255]
# Description
- [X] Symbol: ZYN
- [X] ChainId: 78
- [X] Website: https://wethio.io/
- [X]  Block-Explorer: https://explorer.wethio.io/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: 77777

# Additional comments

First PR #104

**Comment by wethioproject** [comment]
@cseguret-ledger Should we create a new Pull Request to add Wethio network on the ledger app ?

**Comment by Draghtnod** [comment]
This has already been added here: https://github.com/LedgerHQ/app-ethereum/pull/289
