### ISSUE TITLE
Add Fuse network (FUSE)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#257]
# Description
- [X] Symbol: FUSE
- [X] ChainId: 122
- [X] Website: https://fuse.io/
- [X]  Block-Explorer: https://explorer.fuse.io/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: None

# Additional comments

First PR #114

**Comment by vforgeoux-ledger** [comment]
Please follow the [guidelines](https://developers.ledger.com/docs/device-app/develop/code/clone#a---using-the-4460-path) for this chain to be supported.
