### ISSUE TITLE
Add Energy Web Volta Testnet network (VT) 

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#258]
# Description
- [X] Symbol: VT
- [X] ChainId: 73799
- [X] Website: https://voltafaucet.energyweb.org/
- [X]  Block-Explorer: https://volta-explorer.energyweb.org/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: None

# Additional comments

First PR #75

**Comment by Draghtnod** [comment]
This has already been merged here: https://github.com/LedgerHQ/app-ethereum/commit/0e3c0f9263e9339e454fff5d1d9698f743c85344
