### ISSUE TITLE
Add Ambrosus network (AMB)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#259]
# Description
- [X] Symbol: AMB
- [X] ChainId: 16718
- [X] Website: https://ambrosus.io/
- [X]  Block-Explorer: https://explorer.ambrosus.io/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: None

# Additional comments

First PR #177

**Comment by AnmolSirola** [comment]
@cseguret-ledger Can I work on this issue ?

**Comment by vforgeoux-ledger** [comment]
Please follow the [guidelines](https://developers.ledger.com/docs/device-app/develop/code/clone#a---using-the-4460-path) for this chain to be supported.
