### ISSUE TITLE
Add KardiaChain network (KAI)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#261]
# Description
- [X] Symbol: KAI
- [X] ChainId: 24
- [X] Website: https://kardiachain.io/
- [X]  Block-Explorer: https://explorer.kardiachain.io/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: None

# Additional comments

First PR #234

**Comment by Draghtnod** [comment]
This has already been added here: https://github.com/LedgerHQ/app-ethereum/pull/289
