### ISSUE TITLE
Add BitTorrentChain network (BTT)

### ISSUE THREAD

**Issue by cseguret-ledger** [LedgerHQ/app-ethereum#262]
# Description
- [X] Symbol: BTT
- [X] ChainId: 199
- [X] Website: https://bittorrentchain.io/
- [X]  Block-Explorer: https://scan.bittorrentchain.io/
- [X] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: None

# Additional comments

First PR #211

**Comment by Draghtnod** [comment]
This has already been merged here: https://github.com/LedgerHQ/app-ethereum/commit/6b24a045ce2762369c21477725eb0cf4dc74a18a
