### ISSUE TITLE
Outdated Makefile not generating Glyhphs

### ISSUE THREAD

**Issue by Moejoe90** [LedgerHQ/app-ethereum#3]
Apparently the `Makefile` for this project is outdated in regards with the new SDK, more specifically there is a problem with generating the needed glyphs.c/glyphs.h. 
The issue comes from using `log` commands in the `SDK` without referring to Makefile.definitions of log which causes GNU make to break and just output

> file is up to date  

with no error or anything from that regards, i played with the makefile and was able to generate the needed glyphs by using the terminal shell to execute instead of log

**Comment by rstormsf** [comment]
can u be more specific? 
I can see that `src/glyphs.h` and `src/glyphs.c` are empty files...how did u fix it?

**Comment by KBrizzle** [comment]
Was anyone able to find a workaround for this?

**Comment by rstormsf** [comment]
can't remember what I did, but i fixed it
