### ISSUE TITLE
Python examples do not run under Python 3

### ISSUE THREAD

**Issue by kayagoban** [LedgerHQ/app-ethereum#30]
I'm trying to use the ledger in a Python project that uses the new web3.py version, which can no longer run under Python 2.  

Is there any chance somebody could do a quick and dirty update to the examples getPublicKey.py, ethBase.py and signTx.py so that they work under Python 3?  Or perhaps include alternative versions of these files that do work under Python 3, in case you want to still keep around versions that work on Python 2?

It would be an enormous help!

**Comment by clementperon** [comment]
https://github.com/LedgerHQ/ledger-app-eth/pull/50
