### ISSUE TITLE
Add Aurora network (ETH)

### ISSUE THREAD

**Issue by sept-en** [LedgerHQ/app-ethereum#304]
## Description
- [ ] Symbol: ETH
- [ ] ChainId: 1313161554
- [ ] Website: https://aurora.dev/
- [ ] Block-Explorer: https://aurorascan.dev/
- [ ] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: 60

**Comment by vforgeoux-ledger** [comment]
Please follow the [guidelines](https://developers.ledger.com/docs/device-app/develop/code/clone#a---using-the-4460-path) for this chain to be supported.
