### ISSUE TITLE
Inputting seed words from Ethereum Staking-Deposit-CLI should add wallets of staked ETH 2.0 to Ledger

### ISSUE THREAD

**Issue by jeffersonwarrior** [LedgerHQ/app-ethereum#389]
## Description

Describe your issue in as much detail as possible here.

## Your environment

* OS and version - Linux
* branch that causes this issue - Any
* Device (Nano S, Nano X, Ledger Blue) - Nano X

## Steps to reproduce

* Tell us how to reproduce this issue <br />
  
     Use Staking-Deposit-CLI, stake 32 Ethereum, input 24 seed words into a fresh Nano X, note that adding ETH Wallets to Ledger Live does not show the Staked 32 Ethereum 
  
* Where the issue is, if you know <br />

   Somewhere between this app and Ledger Live, the wallet does not detect the wallet from the words generated by Staking-Deposit-CLI

* Which commands triggered the issue, if any

Adding wallet to Ledger Live

## Expected behaviour

It should show the 32 Ethereum (or more) staked from Staking-Deposit-CLI wallet words

## Actual behaviour

The account does not show any staked Ethereum

## Logs

Available upon request

## Proposed solution

Check generating 24 words from https://github.com/ethereum/staking-deposit-cli/releases/  << this project, add 32 ethereum staked and see if it comes up on Ledger Live / Ledger.

**Comment by adrienlacombe-ledger** [comment]
@jeffersonwarrior this is an enhancement request to be done on Ledger Live side, not here, thank you.

**Comment by jeffersonwarrior** [comment]
@adrienlacombe-ledger So does the Ethereum app natively support the 24 words generated by the Staking-Deposit-Cli? Because if it does not, then Ledger Live will not work.

**Comment by adrienlacombe-ledger** [comment]
It does but it won't achieve what you expect, if you want to see your staked ETH in Ledger Live, this is an issue with Ledger Live, not the ethereum nano app.

**Comment by jeffersonwarrior** [comment]
Moving to Ledger Live
