### ISSUE TITLE
Ledger Firefox U2F support

### ISSUE THREAD

**Issue by kvhnuke** [LedgerHQ/app-ethereum#40]
I ran across a very interesting issue while trying to add firefox support for ledger on MEW since now firefox natively supports U2F
it seems like Firefox sends `u2f.register` request to ledger instead of `u2f.sign`. I was able to verify this by using Fido U2F app on ledger nano s. The moment I try to send a `sign` request, firefox for some reason convert it to a `register` request and sends it out. This might be due to the fact that the browser remembers whether the device is registered before or not, and based on u2f standard flow you cannot sign without registering first. In order to solve this issue, ledger-app-eth might have to catch the register event as well

you can verify this issue by using ledgerjs lib on firefox. Or refer to our branch
https://github.com/kvhnuke/etherwallet/pull/2135

**Comment by graemeblackwood** [comment]
Probably an issue for all Ledger apps, but I would also like to see support for Firefox solved. This looks like a logical place to start.

**Comment by polyzen** [comment]
Shouldn't this belong in https://github.com/LedgerHQ/ledger-app-u2f?

**Comment by kvhnuke** [comment]
I believe https://github.com/LedgerHQ/ledger-app-u2f is the Fido U2F app, which works without any issues. This issue applies to the way ledger handling U2F on crypto apps

**Comment by RoboUpTrend** [comment]
https://addons.mozilla.org/en-US/firefox/addon/ledger-live

**Comment by kvhnuke** [comment]
Looks like a phishing scam, don't click the above link
