### ISSUE TITLE
Error pulling up app on local using Nano S plus

### ISSUE THREAD

**Issue by Sj-001** [LedgerHQ/app-ethereum#417]
I am trying to build and load the app using the ledger documentation. When I run the following command in the terminal,

python3 -m ledgerblue.loadApp --curve  secp256k1 --appFlags 0xa40 --path "44'/60'" --tlv --targetId 0x33100004 --targetVersion="2.1.0" --delete --fileName bin/app.hex --appName "Ethereum" --appVersion "1.10.2" --dataSize $((0x\`cat debug/app.map |grep _envram_data | tr -s ' ' | cut -f2 -d' '|cut -f2 -d'x'\` - 0x\`cat debug/app.map |grep _nvram_data | tr -s ' ' | cut -f2 -d' '|cut -f2 -d'x'\`)) \`ICONHEX="0100000000ffffff00000000000c0003e00178003f8007100278001e000300000000" ; [ ! -z "$ICONHEX" ] && echo "--icon $ICONHEX"\`

 It gives me the below error:

`Generated random root public key : b'041555a24459c0632da9cb9ef1a8830fef2f40059e0c0ba5e6889a4f5662d47af6d52c302af71b9de4df3530da9f95df591f2384394fbb4a0b6854f806dcf14a9a'
Using test master key b'041555a24459c0632da9cb9ef1a8830fef2f40059e0c0ba5e6889a4f5662d47af6d52c302af71b9de4df3530da9f95df591f2384394fbb4a0b6854f806dcf14a9a' 
Using ephemeral key b'048e2ef11e01cca41021f5c34cfc081fa3ff4e06b730edce5203f4902b7295a19b935493c82bce263b5c783386be7d7693942095567722f34ec1a1acd3bb0eebc1'
Broken certificate chain - loading from user key
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/Library/Frameworks/Python.framework/Versions/3.10/lib/python3.10/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/Users/sj/Desktop/ledger-app-ethereum/ledger/lib/python3.10/site-packages/ledgerblue/loadApp.py", line 253, in <module>
    loader.createApp(code_length, args.apiLevel, args.dataSize, paramsSize, args.appFlags, args.bootAddr|1)
  File "/Users/sj/Desktop/ledger-app-ethereum/ledger/lib/python3.10/site-packages/ledgerblue/hexLoader.py", line 346, in createApp
    self.exchange(self.cla, 0x00, 0x00, 0x00, data)
  File "/Users/sj/Desktop/ledger-app-ethereum/ledger/lib/python3.10/site-packages/ledgerblue/hexLoader.py", line 189, in exchange
    return self.scpUnwrap(bytes(self.card.exchange(apdu)))
  File "/Users/sj/Desktop/ledger-app-ethereum/ledger/lib/python3.10/site-packages/ledgerblue/comm.py", line 151, in exchange
    raise CommException("Invalid status %04x (%s)" % (sw, possibleCause), sw, response)
ledgerblue.commException.CommException: Exception : Invalid status 6512 (Unknown reason)
`

**Comment by Sj-001** [comment]
@abonnaudet-ledger Can you please look into it?

**Comment by apaillier-ledger** [comment]
Hello @Sj-001, by the lack of an `--apiLevel` argument to the `python3` command, I'm guessing you are using an outdated [SDK](https://github.com/LedgerHQ/ledger-secure-sdk/).
To prevent these kind of version mismatch, I recommend you to simply use the [app-builder](https://github.com/LedgerHQ/ledger-app-builder/) and make sure you always use the latest version. :+1:

**Comment by Sj-001** [comment]
Hey @apaillier-ledger , thanks for following up.

https://developers.ledger.com/docs/embedded-app/eth-app-update/ I am following this section and I don't see the sdk that you mentioned.

**Comment by apaillier-ledger** [comment]
In that case, in the [Build the Application](https://developers.ledger.com/docs/embedded-app/eth-app-update/#build-the-application) section, it already tells you to use the [app-builder](https://developers.ledger.com/docs/embedded-app/app-builder-container/).
This docker container already includes the necessary SDK, just make sure you have the latest version with a `docker pull`. :+1:
