### ISSUE TITLE
Add NEON EVM DEVNET network (NEON)

### ISSUE THREAD

**Issue by Sj-001** [LedgerHQ/app-ethereum#428]
## Description
- [x] Symbol: NEON
- [x] ChainId: 245022926
- [x] Website: https://neon-labs.org/
- [x] Block-Explorer: https://blockscout.com/neon/devnet/
- [x] [slip-0044](https://github.com/satoshilabs/slips/blob/master/slip-0044.md) type: 1
--

## Additional comments

Please post additional comments in this section if you have them, otherwise delete it.

**Comment by Sj-001** [comment]
@apaillier-ledger Can you please help process this?

**Comment by vforgeoux-ledger** [comment]
Closing it as it has been added already https://github.com/LedgerHQ/app-ethereum/blob/189a5bf788b7f9ed8f6eed9b63c9cd64a23119f9/src/network.c#L74
