### ISSUE TITLE
[UI] stax/nano inconsistency

### ISSUE THREAD

**Issue by jmartins-ledger** [LedgerHQ/app-ethereum#452]
https://github.com/LedgerHQ/app-ethereum/blob/f0df04a91efff531befd040a0454b2ffb2dc6cb8/src_nbgl/ui_stark_transfer.c#L49-L52

When there is a self conditional transaction this field is not displayed on the nano.

**Comment by cedelavergne-ledger** [comment]
Closing because starkware is no more in ethereum app
