### ISSUE TITLE
Has Ledger ever used Libbitcoin?

### ISSUE THREAD

**Issue by hanniabu** [LedgerHQ/app-ethereum#462]
Libbitcoin Explorer (bx seed), used by many crypto wallets to generate private key entropy, is flawed and hackers have been silently draining people's money across multiple blockchains. https://milksad.info/

Has Ledger ever used Libbitcoin?

**Comment by adrienlacombe-ledger** [comment]
does it have anything to do with Ethereum?

**Comment by hanniabu** [comment]
They also supported Ethereum signing but it was answered on Twitter that Ledger doesn't use this library
