### ISSUE TITLE
Please don't hide non zero amounts while blind signing

### ISSUE THREAD

**Issue by 0x398** [LedgerHQ/app-ethereum#695]
Please don't hide non zero amounts! It is usually zero, but I want to know when it is not. This way you hiding when some rogue smart contact want to steal ETH! 

_Originally posted by @0x398 in https://github.com/LedgerHQ/app-ethereum/pull/692#issuecomment-2540205455_

**Comment by vforgeoux-ledger** [comment]
You're right @0x398 , the purpose of the PR https://github.com/LedgerHQ/app-ethereum/pull/692 has two objectives: 
1. Introduce the transaction hash to highlight that some data hasn't been decoded in this transaction.
2. Hide the ETH amount when it's 0 as it give a false sense of safety -> other tokens might be transferred for instance.
 
But it's true that when ETH amount isn't 0, it doesn't make sense to hide it. 
The team is currently working on preparing a PR to fix this.
