### ISSUE TITLE
My main adress from my Ledger Nano S is not showing up in MEW or mycrypto

### ISSUE THREAD

**Issue by Falsetto286** [LedgerHQ/app-ethereum#97]
Need your help guys.
I have been using my ledger with MEW for the past 3years but since I updated firmware my main address does not show up in MEW/Mycrypto/LL anymore. 
I tried looking for the address on findeth but noting to be found, its like my adress never existed.

I checked the wallet on etherscan and my funds are still there but I have no way to access.

 I also tried different derivation paths but it still doesn't show up.

Hope you guys can help me out or all my eth will be lost in nirvana......

**Comment by pscott** [comment]
@Falsetto286 Have you managed to solve your issue?
